import React from 'react';
import { HelpCircle, CheckCircle2, ShieldCheck, AlertOctagon, Info } from 'lucide-react';

export default function ScoreExplainability({ score, riskLevel, breakdown, isHero }) {
  return (
    <div className="bg-slate-900/90 border border-slate-800 p-4 rounded-xl shadow-xl space-y-4">
      
      {/* Header & Final Urgency Score */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-3">
        <div>
          <div className="flex items-center gap-2">
            <h4 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-1.5">
              Explainable Urgency Breakdown
            </h4>
            <span className="text-[10px] bg-cyan-950 text-cyan-400 border border-cyan-800 px-1.5 py-0.5 rounded font-mono">
              Transparent Scoring
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Audit-ready rationale generated by ForeSite Decision Engine
          </p>
        </div>

        <div className="text-right">
          <div className="text-2xl font-black font-mono text-cyan-400">
            {score}<span className="text-xs text-slate-500 font-normal">/100</span>
          </div>
          <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded font-mono ${
            riskLevel === 'Critical' ? 'bg-rose-950 text-rose-300 border border-rose-800' :
            riskLevel === 'High' ? 'bg-amber-950 text-amber-300 border border-amber-800' :
            riskLevel === 'Medium' ? 'bg-yellow-950 text-yellow-300 border border-yellow-800' :
            'bg-emerald-950 text-emerald-300 border border-emerald-800'
          }`}>
            {riskLevel} Risk Tier
          </span>
        </div>
      </div>

      {/* Factor Breakdown List */}
      <div className="space-y-2.5">
        {breakdown?.map((item, idx) => (
          <div key={idx} className="bg-slate-950/70 border border-slate-800/80 p-2.5 rounded-lg">
            <div className="flex items-center justify-between text-xs mb-1">
              <span className="font-semibold text-slate-200">{item.factor}</span>
              <span className="font-mono font-bold text-cyan-300">
                +{item.points} <span className="text-slate-500 text-[10px]">/ {item.max_points} pts</span>
              </span>
            </div>
            
            <p className="text-[11px] text-slate-400 font-mono mb-1.5">
              {item.description}
            </p>

            <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden">
              <div
                className="bg-cyan-500 h-full rounded-full transition-all duration-300"
                style={{ width: `${(item.points / item.max_points) * 100}%` }}
              ></div>
            </div>
          </div>
        ))}
      </div>

      {/* Human-in-the-loop Governance Banner */}
      <div className="bg-cyan-950/40 border border-cyan-800/60 p-2.5 rounded-lg flex items-start gap-2 text-[11px]">
        <Info className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
        <p className="text-slate-300 leading-snug">
          <strong className="text-cyan-300">Human-in-the-Loop Protocol:</strong> AI identifies and prioritizes potential cases based on Earth Observation data. Officials inspect in field and make final legal determinations.
        </p>
      </div>

    </div>
  );
}
